name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t europe-central2-docker.pkg.dev/speak-mate-mvp/backend-image/backend:latest \
            --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend \
            --image=europe-central2-docker.pkg.dev/speak-mate-mvp/backend-image/backend:latest \
            --region=europe-central2 \
            --platform=managed \
            --allow-unauthenticated
